### ISSUE TITLE
new-pipeline-composition: `spec.environment` wrongly pushed down entirely to function

### ISSUE THREAD

**Issue by phisco** [crossplane-contrib/crossplane-migrator#18]
Currently the `new-pipeline-composition` command takes the whole `spec.environment` and moves it down to `spec.pipeline[0].environment`, but that's not correct, only `spec.environment.patches` should be pushed down at the Function level, while the rest should be kept at the Composition level.

This is most probably due to the drift between the [vendored](https://github.com/crossplane-contrib/crossplane-migrator/blob/19c1a70eaf79031c698511abd6b610aff7b266f6/newpipeinecomposition/converter.go#L169) `Input` and the actual `Resources` [expected](https://github.com/crossplane-contrib/function-patch-and-transform/blob/f6c8462ad358fe7a1f41be7632964f3ae37f0343/input/v1beta1/resources.go#L19) by `function-patch-and-transform`.

**Comment by stevendborrelli** [comment]
Reopening issue as per https://github.com/crossplane-contrib/crossplane-migrator/pull/19#pullrequestreview-1750811449
